const fs=require('fs');
const ROOT='/Users/muhammaduzair/www/chegatta.com';
const geob=fs.readFileSync(ROOT+'/geofence-construction-staffing.html','utf8');
const qrEn=fs.readFileSync(ROOT+'/qr-code-employee-clock-in.html','utf8');
const bES=fs.readFileSync(ROOT+'/es/prevent-buddy-punching.html','utf8');
const bPT=fs.readFileSync(ROOT+'/pt/prevent-buddy-punching.html','utf8');
function navOf(s){const m=s.match(/<nav class="navbar"[\s\S]*?<\/nav>/);return m?m[0]:''}
function footOf(s){const m=s.match(/<footer class="footer">[\s\S]*?<\/footer>/);return m?m[0]:''}
if(!navOf(bES)||!footOf(bES)||!navOf(bPT)||!footOf(bPT)){console.error('EXTRACTION FAILED nav/foot');process.exit(1);}
const navES=navOf(bES),footES=footOf(bES),navPT=navOf(bPT),footPT=footOf(bPT);
const slug={geof:'geofence-construction-staffing',qr:'qr-code-employee-clock-in'};
const D=[
["Geofence Time Tracking for Construction Staffing \u2014 Chegatta","Control de horas con geovallas para el personal de construcción \u2014 Chegatta","Controle de Ponto com Geofence para Terceirização de Construção \u2014 Chegatta"],
["QR Code Employee Clock-In System \u2014 Chegatta","Sistema de fichaje de empleados con código QR \u2014 Chegatta","Sistema de Controle de Ponto com Código QR para Funcionários \u2014 Chegatta"],
["Geofence Time Tracking for Construction Staffing","Control de horas con geovallas para el personal de construcción","Controle de Ponto com Geofence para Terceirização de Construção"],
["QR Code Employee Clock-In System","Sistema de fichaje de empleados con código QR","Sistema de Controle de Ponto com Código QR para Funcionários"],
["Geofence time tracking for construction staffing agencies. GPS-verified clock-in at job sites, automatic overtime tracking, and compliance reporting. Start your free trial.","Control de horas con geovallas para agencias de personal de construcción. Fichaje verificado por GPS en obras, horas extra automáticas e informes de cumplimiento. Empiece su prueba gratuita.","Controle de ponto com geofence para agências de terceirização de construção. Registro verificado por GPS nas obras, horas extras automáticas e relatórios de conformidade. Comece sua avaliação gratuita."],
["QR code employee clock-in system for staffing agencies. Workers scan a QR code at the client site to clock in with GPS verification. Automatic breaks and overtime. Start your free trial.","Sistema de fichaje con código QR para empleados de agencias de personal. Los trabajadores escanean un código QR en el cliente para fichar con verificación de GPS. Descansos y horas extra automáticos. Comience su prueba gratuita.","Sistema de controle de ponto com código QR para funcionários de agências de terceirização. Os funcionários escaneiam um código QR no cliente para registrar com verificação de GPS. Intervalos e horas extras automáticos. Comece sua avaliação gratuita."],
["GPS-verified clock-in at construction job sites. Automatic overtime, compliance reporting, and real-time visibility for construction staffing agencies.","Fichaje verificado por GPS en obras de construcción. Horas extra automáticas, informes de cumplimiento y visibilidad en tiempo real para agencias de personal de construcción.","Registro de ponto verificado por GPS em locais de construção. Horas extras automáticas, relatórios de conformidade e visibilidade em tempo real para agências de terceirização de construção."],
["QR code clock-in with GPS verification. Workers scan a code at the client site, and the system verifies their location. Automatic breaks and overtime tracking.","Fichaje con código QR y verificación de GPS. Los trabajadores escanean un código en el sitio cliente, y el sistema verifica su ubicación. Descansos y seguimiento de horas extras automáticos.","Registro de ponto com código QR e verificação de GPS. Os funcionários escaneiam um código no local do cliente, e o sistema verifica sua localização. Intervalos e acompanhamento automático de horas extras."],
["Geofence time tracking for construction staffing verifies that workers are physically on the job site when they clock in. Chegatta uses GPS geofencing around each construction site, tracks hours automatically, and flags off-site clock-ins \u2014 so you know your temps actually showed up to work.","El control de horas con geovallas para agencias de personal de construcción verifica que los trabajadores están físicamente en el sitio de trabajo al fichar. Chegatta usa geovallas GPS alrededor de cada obra, registra las horas automáticamente y marca los fichajes fuera de la zona \u2014 para que sepas que tus temporales realmente llegaron a trabajar.","O controle de ponto com geofence para agências de terceirização de construção verifica que funcionários estão fisicamente no local ao bater o ponto. A Chegatta usa geofence GPS ao redor de cada obra, registra as horas automaticamente e sinaliza batidas fora do local \u2014 para que você saiba que seus temporários realmente chegaram para trabalhar."],
["A QR code employee clock-in system lets workers scan a code at the client site to clock in, while GPS verification proves they're actually there. Chegatta combines QR scanning with GPS geofencing for double verification, tracks breaks and overtime automatically, and needs no app installation.","Un sistema de fichaje con código QR para empleados permite a los trabajadores escanear un código en el sitio del cliente para fichar, mientras la verificación de GPS prueba que están realmente allí. Chegatta combina el escaneo de códigos QR con geovallas GPS para doble verificación, registra descansos y horas extra automáticamente y no requiere instalación de app.","Um sistema de controle de ponto com código QR para funcionários permite que trabalhadores escaneiem um código no local do cliente para bater o ponto, enquanto a verificação de GPS comprova que eles estão realmente lá. A Chegatta combina a leitura de códigos QR com geofence GPS para dupla verificação, rastreia intervalos e horas extras automaticamente e não requer instalação de app."],
["<span class=\"section-tag\">Construction</span>","<span class=\"section-tag\">Construcción</span>","<span class=\"section-tag\">Construção</span>"],
["<span class=\"section-tag\">QR Code</span>","<span class=\"section-tag\">Código QR</span>","<span class=\"section-tag\">Código QR</span>"],
["<h1 class=\"section-title\">Geofence time tracking for construction staffing</h1>","<h1 class=\"section-title\">Control de horas con geovallas para el personal de construcción</h1>","<h1 class=\"section-title\">Controle de Ponto com Geofence para terceirização de construção</h1>"],
["<h1 class=\"section-title\">QR code employee clock-in system</h1>","<h1 class=\"section-title\">Sistema de fichaje de empleados con código QR</h1>","<h1 class=\"section-title\">Sistema de Controle de Ponto com Código QR para Funcionários</h1>"],
["Why You Need It","Por qué lo necesitas","Porque Você Precisa"],
["Construction sites are everywhere \u2014 your tracking should cover them all","Las obras de construcción están en todas partes \u2014 tu control debería cubrirlas todas","Os locais de construção estão em todo lugar \u2014 seu controle deve cobrir todos"],
["Construction staffing agencies place workers across multiple job sites, often in different cities. Each site has different hours, overtime rules, and safety requirements. You need a system that verifies workers are on site, tracks their hours accurately, and gives you compliance-ready reports.","Las agencias de personal de construcción colocan trabajadores en múltiples obras, a menudo en diferentes ciudades. Cada obra tiene diferentes horas, normas de horas extra y requisitos de seguridad. Necesitas un sistema que verifique que los trabajadores están en el sitio, rastree sus horas con precisión y te ofrezca informes listos para cumplir.","As agências de terceirização de construção colocam funcionários em múltiplos locais, muitas vezes em cidades diferentes. Cada local tem horas diferentes, regras de horas extras e requisitos de segurança. Você precisa de um sistema que verifique se os funcionários estão no local, rastreie suas horas com precisão e ofereça relatórios de conformidade prontos."],
["QR codes add an extra layer of verification","Los códigos QR añaden una capa extra de verificación","Os códigos QR adicionam uma camada extra de verificação"],
["QR codes at client sites prove workers are physically present, not just claiming they showed up. Combined with GPS verification, you get double proof of attendance. QR codes are also fast \u2014 workers scan and clock in in seconds.","Los códigos QR en los sitios del cliente prueban que los trabajadores están físicamente presentes, no solo que dicen haber venido. Combinados con la verificación de GPS, obtienes una doble prueba de asistencia. Los códigos QR también son rápidos \u2014 los trabajadores escanean y fichan en segundos.","Códigos QR nos locais do cliente comprovam que os funcionários estão fisicamente presentes, não apenas reivindicando que compareceram. Combinados com a verificação de GPS, você obtém uma dupla comprovação de presença. Os códigos QR também são rápidos \u2014 os funcionários escaneiam e batem o ponto em segundos."],
["Job site geofencing","Geovallas en el sitio de trabajo","Geofence no local de trabalho"],
["Draw a geofence around each construction site. Workers can only clock in when they're inside the fence, so you know they're actually on site.","Dibuje una geovalla alrededor de cada obra. Los trabajadores solo pueden fichar dentro de la cerca, así sabe que están en el sitio.","Desenhe um geofence ao redor de cada obra. Os trabalhadores só podem bater o ponto dentro da cerca, assim você sabe que estão no local."],
["Multi-site management","Gestión multi-local","Gestão multi-local"],
["Manage unlimited construction sites from one dashboard. Each site has its own geofence, shift rules, and crew assignments.","Gestione obras ilimitadas desde un panel. Cada obra tiene su propia geovalla, normas de turno y asignaciones de cuadrilla.","Gerencie locais de construção ilimitados a partir de um painel. Cada local tem seu próprio geofence, regras de escala e atribuições de equipe."],
["Automatic overtime tracking","Horas extra automáticas","Controle automático de horas extras"],
["Construction often involves overtime. Chegatta calculates overtime automatically against each site's rules, so payroll is accurate every time.","La construcción suele implicar horas extra. Chegatta calcula las horas extra automáticamente según las normas de cada obra, por lo que la nómina es precisa siempre.","A construção frequentemente envolve horas extras. A Chegatta calcula horas extras automaticamente conforme as regras de cada local, então a folha de pagamento é sempre precisa."],
["Compliance reporting","Informes de cumplimiento","Relatórios de conformidade"],
["Generate reports showing who worked when, with GPS proof. Perfect for union requirements, client billing, and labor law compliance.","Genere informes que muestran quién trabajó cuándo, con prueba GPS. Perfecto para requisitos sindicales, facturación al cliente y cumplimiento normativo.","Gerar relatórios mostrando quem trabalhou quando, com prova de GPS. Perfeito para requisitos sindicais, faturamento ao cliente e conformidade trabalhista."],
["Weather-proof clock-in","Fichaje a prueba de intempéries","Registro resistente a intempéries"],
["Workers clock in from their phone, even in bad weather. No more paper timesheets that get wet, lost, or damaged on site.","Los trabajadores fichan desde su teléfono, incluso con mal tiempo. Adiós a las hojas de horas en papel que se mojan, pierden o dañan en la obra.","Os funcionários batem o ponto pelo celular, mesmo em clima ruim. Sem mais folhas de ponto em papel que ficam molhadas, perdidas ou danificadas no local."],
["Crew assignment tracking","Seguimiento de cuadrillas","Rastreamento de equipes"],
["Assign crews to specific sites and shifts. See which workers are assigned where, and track attendance by crew or by site.","Asigne cuadrillas a obras y turnos específicos. Vea qué trabajadores están asignados dónde y rastree la asistencia por cuadrilla o por obra.","Atribua equipes a locais e escalas específicos. Veja quais funcionários estão atribuídos onde e rastreie a presença por equipe ou por local."],
["How It Works","Cómo funciona","Como Funciona"],
["From signup to verified hours in one afternoon","De la inscripción a horas verificadas en una tarde","Do cadastro às horas verificadas em uma tarde"],
["Add your client companies","Añade tus empresas cliente","Adicione as suas empresas clientes"],
["Create each client company in Chegatta and drop a geofence on every worksite where your workers operate.","Cree cada empresa cliente en Chegatta y coloque una geovalla en cada obra donde operan sus trabajadores.","Crie cada empresa cliente na Chegatta e adicione um geofence em cada local de trabalho onde seus funcionários operam."],
["Assign workers to assignments","Asigna trabajadores a las asignaciones","Atribua trabalhadores às atribuições"],
["Invite employees by email, assign them to one or more client companies, and set shift rules for breaks and overtime.","Invite a empleados por correo, asígnalos a una o más empresas cliente y establezca normas de turno para descansos y horas extra.","Convidar funcionários por e-mail, atribuí-los a uma ou mais empresas clientes e definir regras de escala para intervalos e horas extras."],
["Track every worker in real time","Sigue a cada trabajador en tiempo real","Siga a cada funcionário em tempo real"],
["Workers clock in from their phone at any client location. You see verified attendance across all companies, with anomalies flagged automatically.","Los trabajadores fichan desde su teléfono en cualquier sede del cliente. Ves la asistencia verificada en todas las empresas, con anomalías marcadas automáticamente.","Os funcionários batem o ponto pelo celular em qualquer local do cliente. Você vê a presença verificada em todas as empresas, com anomalias sinalizadas automaticamente."],
["Geolocation Clock-In","Fichaje por Geolocalización","Registo de Ponto por Geolocalização"],
["GPS-verified clock-in with per-worksite geofencing. Every hour claimed is an hour actually worked at the right client location.","Fichaje verificado por GPS con geovallas por obra. Cada hora declarada es una hora realmente trabajada en la sede del cliente correcta.","Registo de ponto verificado por GPS com geofence por local de trabalho. Cada hora declarada é uma hora realmente trabalhada no local do cliente certo."],
["Multi-Company Assignment","Asignación Multiempresa","Atribuição Multiempresa"],
["Assign employees to multiple client companies, track assignment history, rotate workers between sites, and keep a full audit trail.","Asigne empleados a varias empresas cliente, rastree el historial de asignaciones, rote trabajadores entre sitios y mantenga un registro completo.","Atribua funcionários a várias empresas clientes, rastreie o histórico de atribuições, gire funcionários entre locais e mantenha um histórico completo."],
["Break &amp; Overtime Tracking","Descansos y Horas Extra","Pausas e Horas Extra"],
["Automatic break detection and overtime calculation per client shift rules. Payroll and client billing use verified, exported hours.","Detección automática de descansos y cálculo de horas extra según las normas de escala del cliente. La nómina y la facturación usan horas verificadas y exportadas.","Detecção automática de intervalos e cálculo de horas extras segundo as regras de escala de cada cliente. A folha de pagamento e o faturamento usam horas verificadas e exportadas."],
["See All Features","Ver todas las funciones","Ver Todos os Recursos"],
["Attendance Insights","Información de Asistencia","Informações de Presença"],
["Live","En vivo","Ao vivo"],
["Present Today","Presentes hoy","Presentes hoje"],
["Late Arrivals","Llegadas tardías","Atrasos"],
["Off-Site","Fuera del sitio","Fora do local"],
["Overtime","Horas extra","Horas extras"],
["2 employees need attention across 3 client sites.","2 empleados necesitan atención en 3 sitios cliente.","2 funcionários precisam de atenção em 3 locais de clientes."],
["Start your 14-day free trial today. No credit card required. Full access to all features.","Comience su prueba gratuita de 14 días hoy. Sin necesidad de tarjeta de crédito. Acceso completo a todas las funciones.","Comece o seu teste gratuito de 14 dias hoje. Sem cartão de crédito. Acesso completo a todas as funcionalidades."],
["Start My Free Trial","Comienza mi prueba gratuita","Comece o teste grátis"],
["Request a Demo","Solicitar demo","Solicitar demonstração"],
["No credit card required \u00b7 14 days full access \u00b7 Cancel anytime \u00b7 Setup in 5 minutes","Sin necesidad de tarjeta de crédito \u00b7 14 días de acceso completo \u00b7 Cancela en cualquier momento \u00b7 Configuración en 5 minutos","Sem cartão de crédito \u00b7 14 dias de acesso completo \u00b7 Cancele quando quiser \u00b7 Instalação em 5 minutos"],
["Why You Need It"/*d*/,"Por qué lo necesitas","Porque Você Precisa"],
["Comparison","Comparación","Comparação"],
["Features","Características","Recursos"],
["<span class=\"section-tag\">FAQ</span>","<span class=\"section-tag\">Preguntas frecuentes</span>","<span class=\"section-tag\">Perguntas frequentes</span>"],
["How Chegatta compares to construction time clocks","Cómo Chegatta se compara con los relojes de tiempo industriales","Como a Chegatta se compara aos relógios de ponto industriais"],
["Physical time clocks are fixed to one location and can be bypassed. Chegatta goes wherever your workers go.","Los relojes de tiempo físicos están fijos en un lugar y pueden evitarse. Chegatta va donde vayan sus trabajadores.","Os relógios de ponto físicos são fixos em um local e podem ser contornados. A Chegatta vai aonde seus funcionários vão."],
["Mobile geofencing","Geovallas móviles","Geofence móvel"],
["Workers clock in from their phone at any job site. No need to install physical time clocks at every location.","Los trabajadores fichan desde su teléfono en cualquier obra. No necesita instalar relojes físicos en cada ubicación.","Os funcionários batem o ponto pelo celular em qualquer obra. Não é necessário instalar relógios físicos em cada local."],
["GPS verification","Verificación GPS","Verificação de GPS"],
["Every clock-in includes GPS coordinates, proving the worker was on site. No more buddy punching or false clock-ins.","Cada fichaje incluye coordenadas GPS, probando que el trabajador estaba en el sitio. Adiós al timbirite o fichajes falsos.","Cada batida de ponto inclui coordenadas de GPS, comprovando que o funcionário estava no local. Sem mais 'buddy punching' ou batidas falsas."],
["Multi-site from one dashboard","Multi-sitio desde un panel","Multi-local a partir de um painel"],
["See attendance across all construction sites in real time. No more calling site supervisors to ask who showed up.","Vea la asistencia en todas las obras en tiempo real. Adiós a llamar a supervisores para preguntar quién vino.","Veja a presença em todos os locais de construção em tempo real. Sem mais ligar para supervisores para perguntar quem veio."],
["Automatic compliance reports","Informes de cumplimiento automáticos","Relatórios de conformidade automáticos"],
["Generate compliance-ready reports with GPS proof. No more manually compiling timesheets for union or client requirements.","Genere informes listos para cumplir con prueba GPS. Adiós a compilar manualmente hojas de horas para requisitos sindicales o del cliente.","Gerar relatórios de conformidade prontos com prova de GPS. Sem mais compilando manualmente folhas de ponto para requisitos sindicais ou do cliente."],
["How Chegatta compares to basic QR clock-in systems","Cómo Chegatta se compara con sistemas básicos de fichaje QR","Como a Chegatta se compara a sistemas básicos de ponto com QR"],
["Most QR clock-in systems only verify the code was scanned. Chegatta verifies the code AND the worker's location.","La mayoría de los sistemas de fichaje QR solo verifican que el código fue escaneado. Chegatta verifica el código Y la ubicación del trabajador.","A maioria dos sistemas de ponto com QR apenas verifica que o código foi escaneado. A Chegatta verifica o código E a localização do funcionário."],
["GPS + QR verification","Verificación de GPS + QR","Verificação de GPS + QR"],
["Scanning the QR code isn't enough \u2014 Chegatta also verifies the worker's GPS position matches the worksite.","Escanear el código QR no es suficiente \u2014 Chegatta también verifica que la posición GPS del trabajador coincide con el sitio.","Escanear o código QR não é suficiente \u2014 a Chegatta também verifica se a posição de GPS do funcionário corresponde ao local."],
["No app required","Sin app necesaria","Sem app necessário"],
["Workers use their phone's built-in camera. No app store downloads, no onboarding friction for temporary workers.","Los trabajadores usan la cámara incorporada de su teléfono. Sin descargas de app store, sin fricción de incorporación para trabajadores temporales.","Os funcionários usam a câmera incorporada no telefone. Sem downloads de app store, sem atrito de onboarding para trabalhadores temporários."],
["Generate QR codes for unlimited worksites. Each site has its own code, geofence, and shift rules.","Genere códigos QR para obras ilimitadas. Cada obra tiene su propio código, geovalla y normas de turno.","Genere códigos QR para locais ilimitados. Cada local tem seu próprio código, geofence e regras de escala."],
["Automatic calculations","Cálculos automáticos","Cálculos automáticos"],
["Breaks and overtime are calculated automatically. No manual timesheet review or arithmetic.","Los descansos y horas extra se calculan automáticamente. Sin revisión manual de hojas de horas ni aritmética.","Intervalos e horas extras são calculados automaticamente. Sem revisão manual de folhas de ponto ou aritmética."],
["Everything construction staffing agencies need","Todo lo que las agencias de personal de construcción necesitan","Tudo o que as agências de terceirização de construção precisam"],
["Everything you need for QR code clock-in","Todo lo que necesitas para registrar con código QR","Tudo o que você precisa para registrar com código QR"],
["Geofence time tracking for construction, questions answered","Control de horas con geovallas para la construcción: preguntas respondidas","Controle de ponto com geofence para construção: perguntas respondidas"],
["QR code employee clock-in, questions answered","Sistema de fichaje con código QR para empleados: preguntas respondidas","Controle de ponto com código QR para funcionários: perguntas respondidas"],
["What is geofence time tracking for construction staffing?","¿Qué es el control de horas con geovallas para el personal de construcción?","O que é o controle de ponto com geofence para agências de contratação de pessoal de construção?"],
["Geofence time tracking uses GPS to verify that construction workers are physically on the job site when they clock in. Chegatta draws a virtual fence around each construction site, and workers can only clock in when they're inside that fence.","El control de horas con geovallas usa GPS para verificar que los trabajadores de construcción están físicamente en el sitio de trabajo al fichar. Chegatta dibuja una cerca virtual alrededor de cada obra, y los trabajadores solo pueden fichar cuando están dentro de esa cerca.","O controle de ponto com geofence usa GPS para verificar que trabalhadores de construção estão fisicamente no local ao bater o ponto. A Chegatta desenha uma cerca virtual ao redor de cada obra, e os funcionários só podem bater o ponto quando estão dentro dessa cerca."],
["How does geofencing prevent buddy punching on construction sites?","¿Cómo evita el geovallado el timbirite (fichaje de otro) en los sitios de construcción?","Como o geofence impede o 'buddy punching' em locais de construção?"],
["When a worker clocks in, Chegatta captures their GPS coordinates and verifies they're inside the site's geofence. If someone tries to clock in for a worker who isn't there, the GPS won't match, and the clock-in is flagged.","Cuando un trabajador ficha, Chegatta captura sus coordenadas GPS y verifica que está dentro de la cerca del sitio. Si alguien intenta fichar por un trabajador que no está allí, el GPS no coincidirá y el fichaje se marcará.","Quando um funcionário bate o ponto, a Chegatta captura suas coordenadas de GPS e verifica se está dentro da cerca do local. Se alguém tentar bater o ponto de um funcionário que não está lá, o GPS não corresponderá e o ponto será sinalizado."],
["Can geofence tracking work across multiple construction sites?","¿Puede el geovallado funcionar en varios sitios de construcción?","O geofence pode funcionar em vários locais de construção?"],
["Yes. Chegatta manages unlimited construction sites, each with its own geofence. You see attendance across all sites from one dashboard, with real-time visibility into who is working where.","Sí. Chegatta gestiona obras de construcción ilimitadas, cada una con su propia geovalla. Ves la asistencia de todos los sitios desde un panel, con visibilidad en tiempo real de quién trabaja dónde.","Sim. A Chegatta gerencia locais de construção ilimitados, cada um com seu próprio geofence. Você vê a presença em todos os locais a partir de um painel, com visibilidade em tempo real de quem está trabalhando onde."],
["Does geofence tracking work in bad weather?","¿El geovallado funciona con mal tiempo?","O geofence funciona em más condições climáticas?"],
["Yes. Workers clock in from their phone, which works in any weather. No more paper timesheets that get wet or damaged on site.","Sí. Los trabajadores fichan desde su teléfono, que funciona en cualquier clima. Adiós a las hojas de horas en papel que se mojan o dañan en la obra.","Sim. Os funcionários batem o ponto pelo celular, que funciona em qualquer clima. Sem mais folhas de ponto em papel que ficam molhadas ou danificadas no local."],
["How does geofence tracking help with compliance?","¿Cómo ayuda el geovallado con el cumplimiento normativo?","Como o geofence ajuda com a conformidade?"],
["Every clock-in includes GPS proof of location. You can generate compliance reports showing exactly who worked when, with location verification \u2014 perfect for union requirements and labor law compliance.","Cada fichaje incluye la prueba GPS de ubicación. Puedes generar informes de cumplimiento que muestran exactamente quién trabajó cuándo, con verificación de ubicación \u2014 perfecto para requisitos sindicales y el cumplimiento de la legislación laboral.","Cada batida de ponto inclui prova de localização por GPS. Você pode gerar relatórios de conformidade mostrando exatamente quem trabalhou quando, com verificação de localização \u2014 perfeito para requisitos sindicais e conformidade com a legislação trabalhista."],
["How much does geofence time tracking for construction cost?","¿Cuánto cuesta el control de horas con geovallas para construcción?","Quanto custa o controle de ponto com geofence para construção?"],
["What is a QR code employee clock-in system?","¿Qué es un sistema de fichaje con código QR para empleados?","O que é um sistema de controle de ponto com código QR para funcionários?"],
["A QR code employee clock-in system lets workers scan a QR code at the worksite to clock in. Chegatta combines QR scanning with GPS verification to prove workers are physically on site, then tracks breaks and overtime automatically.","Un sistema de fichaje con código QR para empleados permite a los trabajadores escanear un código QR en el obra para fichar. Chegatta combina el escaneo de códigos QR con la verificación de GPS para demostrar que los trabajadores están físicamente en el sitio, y luego rastrea descansos y horas extra automáticamente.","Um sistema de controle de ponto com código QR para funcionários permite que trabalhadores escaneiem um código QR no local para bater o ponto. A Chegatta combina a leitura de códigos QR com a verificação de GPS para comprovar que os funcionários estão fisicamente no local, e depois rastreia intervalos e horas extras automaticamente."],
["How does QR code clock-in prevent buddy punching?","¿Cómo evita el fichaje con código QR el timbirite?","Como o controle de ponto com código QR impede o 'buddy punching'?"],
["When a worker scans the QR code, Chegatta also captures their GPS position. Both the QR scan and GPS must match the worksite, so someone can't clock in for a worker who isn't there.","Cuando un trabajador escanea el código QR, Chegatta también captura su posición GPS. Tanto el escaneo del código QR como el GPS deben coincidir con el lugar de trabajo, por lo que alguien no puede fichar por un trabajador que no está allí.","Quando um funcionário escaneia o código QR, a Chegatta também captura sua posição de GPS. Tanto a leitura do código QR quanto o GPS precisam corresponder ao local de trabalho, então alguém não pode bater o ponto de um funcionário que não está lá."],
["Do workers need to install an app to scan QR codes?","¿Necesitan los trabajadores instalar una aplicación para escanear códigos QR?","Os funcionários precisam instalar um aplicativo para escanear códigos QR?"],
["No. Chegatta uses the phone's built-in camera to scan QR codes. No app installation, no account creation, no friction for temporary workers.","No. Chegatta usa la cámara incorporada del teléfono para escanear códigos QR. Sin instalación de aplicaciones, sin creación de cuentas, sin fricción para trabajadores temporales.","Não. A Chegatta usa a câmera incorporada no telefone para escanear códigos QR. Sem instalação de aplicativo, sem criação de conta, sem atrito para trabalhadores temporários."],
["Can QR codes be used at multiple worksites?","¿Los códigos QR se pueden usar en varios lugares de trabajo?","Os códigos QR podem ser usados em vários locais de trabalho?"],
["Yes. Chegatta generates unique QR codes for each worksite. You can manage unlimited sites, each with its own code, geofence, and shift rules.","Sí. Chegatta genera códigos QR únicos para cada lugar de trabajo. Puedes gestionar lugares ilimitados, cada uno con su propio código, geovalla y normas de turno.","Sim. A Chegatta gera códigos QR únicos para cada local de trabalho. Você pode gerenciar locais ilimitados, cada um com seu próprio código, geofence e regras de escala."],
["How does QR clock-in integrate with GPS verification?","¿Cómo se integra el fichaje con código QR con la verificación de GPS?","Como o controle de ponto com código QR se integra com a verificação de GPS?"],
["QR clock-in and GPS verification work together. When a worker scans the QR code, Chegatta captures their GPS position. Both must match the worksite for the clock-in to be valid.","El fichaje con código QR y la verificación de GPS trabajan juntos. Cuando un trabajador escanea el código QR, Chegatta captura su posición GPS. Ambos deben coincidir con el lugar de trabajo para que el fichaje sea válido.","O controle de ponto com código QR e a verificação de GPS trabalham juntos. Quando um funcionário escaneia o código QR, a Chegatta captura sua posição de GPS. Ambos precisam corresponder ao local de trabalho para que o ponto seja válido."],
["How much does a QR code clock-in system cost?","¿Cuánto cuesta un sistema de fichaje con código QR?","Quanto custa um sistema de controle de ponto com código QR?"],
["Chegatta plans start at €49 per month for up to 25 employees and scale with your agency. Every plan includes a 14-day free trial with no credit card required.","Los planes de Chegatta empiezan a partir de 49 €/mes para hasta 25 empleados y escalan con tu agencia. Todo plan incluye una prueba gratuita de 14 días sin necesidad de tarjeta de crédito.","Os planos da Chegatta começam a partir de 49 €/mês para até 25 funcionários e escalam com sua agência. Todo plano inclui um teste grátis de 14 dias sem necessidade de cartão de crédito."],
["Verify your workers are actually on site","Verifica que tus trabajadores están realmente en el sitio","Verifique se seus funcionários estão realmente no local"],
["Double verification, zero friction","Doble verificación, sin fricción","Dupla verificação, zero atrito"],
['href="favicon.svg"','href="../favicon.svg"','href="../favicon.svg"'],
['href="css/style.css"','href="../css/style.css"','href="../css/style.css"'],
['src="js/i18n.js"','src="../js/i18n.js"','src="../js/i18n.js"'],
['src="js/lang-switcher.js"','src="../js/lang-switcher.js"','src="../js/lang-switcher.js"'],
['src="js/main.js"','src="../js/main.js"','src="../js/main.js"'],
['lang="en"','lang="es"','lang="pt"']
];
D.sort((a,b)=>b[0].length-a[0].length);
function tr(en,lang){let o=en;for(const t of D){o=o.split(t[0]).join(lang==='es'?t[1]:t[2]);}return o;}
function fixHead(o,slug,lang){
const L=lang==='es'?{c:'es',url:'es',loc:'es_ES'}:{c:'pt',url:'pt',loc:'pt_BR'};
o=o.replace('lang="en"',`lang="${L.c}"`);
o=o.replace(`<link rel="canonical" href="https://chegatta.com/${slug}.html">`,`<link rel="canonical" href="https://chegatta.com/${L.url}/${slug}.html">`);
o=o.replace(`<meta property="og:url" content="https://chegatta.com/${slug}.html">`,`<meta property="og:url" content="https://chegatta.com/${L.url}/${slug}.html">`);
o=o.replace(`"url": "https://chegatta.com/${slug}.html",`,`"url": "https://chegatta.com/${L.url}/${slug}.html",`);
const oldHl=`    <link rel="alternate" hreflang="en" href="https://chegatta.com/${slug}.html">\n    <link rel="alternate" hreflang="x-default" href="https://chegatta.com/${slug}.html">`;
const newHl=`    <link rel="alternate" hreflang="en" href="https://chegatta.com/${slug}.html">\n    <link rel="alternate" hreflang="${L.c}" href="https://chegatta.com/${L.url}/${slug}.html">\n    <link rel="alternate" hreflang="pt" href="https://chegatta.com/pt/${slug}.html">\n    <link rel="alternate" hreflang="x-default" href="https://chegatta.com/${slug}.html">`;
o=o.replace(oldHl,newHl);
o=o.replace('<meta property="og:image:height" content="630">','<meta property="og:image:height" content="630">\n    <meta property="og:locale" content="'+L.loc+'">');
return o;
}
function build(en,slug,lang){
const buddy=lang==='es'?bES:bPT;
let o=tr(en,lang);
o=fixHead(o,slug,lang);
o=o.replace(/<nav class="navbar"[\s\S]*?<\/nav>/, lang==='es'?navES:navPT);
o=o.replace(/<footer class="footer">[\s\S]*?<\/footer>/, lang==='es'?footES:footPT);
o=o.replace(/href="([a-z][a-z0-9-]*\.html[^"]*)"/g,'href="../$1"');
return o;
}
const jobs=[['geof','geofence-construction-staffing'],['qr','qr-code-employee-clock-in']];
for(const [key,sl] of jobs){const en=key==='geof'?geob:qrEn;fs.writeFileSync(ROOT+'/es/'+sl+'.html',build(en,sl,'es'));fs.writeFileSync(ROOT+'/pt/'+sl+'.html',build(en,sl,'pt'));console.log('OK',sl);}
